libreswan: Autospec creation for update from version 3.31 to version 3.32
Andrew Cagney (1):
      IKEv1: Add NSS KDF support for the Quick Mode KDF

Antony Antony (5):
      Revert "pluto: fix a String length miscalculation"
      testing: addconn-05
      testing: add ikev2-child-rekey-09-windows
      testing: add narrowing explictly on the responder.
      testing: update windows rekey tests

D. Hugh Redelmeier (1):
      security: Fix for CVE-2020-1763

Paul Wouters (53):
      * bump to 3.32
      IKEv1: fixup ikev1_quick.c:1389:21: error: unused variable 'c'
      libipsecconf: left/rightinterface-ip= should not be marked as kt_obsolete
      testing: added ikev1-03-fuzzer
      documentation: update to man page for pluto/whack for statistics commands
      X509: don't try to match up ID on SAN when ID type is ID_DER_ASN1_DN
      testing: add x509/nss-certs.sh to generate certs using NSS
      testing: add ikev2-x509-39-OU-comma
      testing: added ikev2-x509-39-OU-comma to TESTLIST
      documentation: updated CHANGES
      testing: update ikev2-x509-39-OU-comma for 3.32 branch
      testing: no need for require-id-on-certificate=no in ikev2-x509-39-OU-comma
      whack: Add missing ecdsa/sha2 and compat rsa policy options to whack
      testing: added addconn-06-whack-algos
      testing: added addconn-06-whack-algos to TESTLIST
      testing: fixup x509/strongswan-ec-gen.sh
      testing: ikev2-x509-39-OU-comma fixup
      testing: extend ikev2-x509-39-OU-comma with ",," test.
      IKEv2: Do not use fragments if not appropriate (regression from v3.30)
      libipsecconf: support old-style ",," to mean "\," in specifying leftid/rightid for ID_DER_ASN1_DN
      FIPS: Fix FIPS_MIN_RSA_KEY_SIZE to 2048 (it was 3072)
      FIPS: Check for minimum RSA key size should be limited to RSA keys
      FIPS: Another instance of RSA key checking on non-RSA key size.
      testing: sync up addconn-05 from master
      testing: added fips-15-ikev2-x509-key2048
      testing: updated TESTLIST
      documentation: updated CHANGES
      testing: extend algparse with required compile time #ifdef's
      testing: algparse, allow a modp1024 for USE_DH2=true
      testing: update fedora/rhel spec files to run algparse and pluto --selftest
      packaging: BuildRequire nss-tools for certutil call in %check
      testing: added basic-pluto-19-seedbits
      testing: added basic-pluto-19-seedbits to TESTLIST
      testing: add relto checking to basic-pluto-19-seedbits
      FIPS: split fips mode checks from pluto binary check
      FIPS: Do not check fips=1 in /proc, use NSS instead.
      documentation: updated CHANGES
      IKEv2: Support non-narrowed child rekey for narrowing (regression in 3.31)
      documentation: Updated CHANGES, move release date to May 11.
      testing: update fips*/description.txt
      FIPS: algparse.c: call NSS_NoDB_Init(".") to make NSS happy
      testing: fixup algparse-02-fips to the new world
      FIPS: Initialize NSS before calling lsw_get_fips_mode()
      testing: fixup algparse-01 similar to algparse-02-fips
      documentation: updated CHANGES
      FIPS: fixup non-working auto-detect compile time check for NSS
      building: backport of c6969d5d272 rekey impairs
      testing: extract fixups from 743cb8de5 for impair-rekey tests
      testing: fixup from master's ikev2-child-rekey-09-windows
      testing: extend newoe-18-poc-block to test for keyingtries=1
      documentation: update security/ with CVE-2020-1763 information
      documentation: update required NSS version for USE_NSS_PRF
      documenation: remove security patches from security/ directory

Tuomo Soini (3):
      packaging/debian: libreswan Recommends python3
      packaging/debian: fix FreeS/WAN version
      packaging/debian: change libreswan-dbg to Priority: optional